

# excpetion_caught = False

# try:
#     print('we have a problem')

# except NameError:
#     excpetion_caught = True

# print(excpetion_caught)



try:
    print(2/0)

except ZeroDivisionError:
    print("hey buddy you can not divide by zero come on man ")